### ISSUE TITLE
errror after update to 2024.10b0

### ISSUE THREAD

**Issue by andiukas** [chatziko/ha-google-cloud-stt#17]
errror after update to 2024.10b0

Registratorius: homeassistant.setup
Šaltinis: setup.py:497
Pirmą kartą įvyko: 2024 m. rugsėjo 25 d. 22:21:05 (1 įvykiai)
Paskutinį kartą prisijungė: 2024 m. rugsėjo 25 d. 22:21:05

Unable to prepare setup for platform 'google_cloud_stt.stt': Platform not found (cannot import name 'SpeechClient' from 'google.cloud.speech_v1.services.speech' (unknown location)).
